### PR TITLE
Added a few details (Hacktober Fest)

### LINKED ISSUE #24: Add details in data,js (Hacktober Fest)
Hi,

I will add my favorite shows in the data.js file.

Best,
Rehan.

### PR DESCRIPTION
**Pull request by abrehan2**
Hi,

Everything is alright! I have added my details in the end. Rest everything is as it was.

Best,
Rehan.

### CODE REVIEW

**Review by aditeyaS — CHANGES_REQUESTED** [review]
Can you update contributors.md as well?

**Comment by aditeyaS** [comment]
Eg: [PR](https://github.com/aditeyaS/peoples-choice/pull/16/files)

**Review by aditeyaS — APPROVED** [review]

**Comment by abrehan2** [comment]
Should I make a new pr for contributing.md?

**Comment by aditeyaS** [comment]
Nah, it's done

**Pull request merged**
