### PR TITLE
New Added data

### PR DESCRIPTION
**Pull request by Akilan19**
- Added my favorite anime, movie, and TV series 
Please tag under Hacktoberfest 2023

### CODE REVIEW

**Review by aditeyaS — CHANGES_REQUESTED** [review]
Can you update contributors.md and resolve the merge conflicts as well

**Comment by Akilan19** [comment]
Hey,
I have resolved the conflicts and updated the contributors.md also.

**Review by aditeyaS — CHANGES_REQUESTED** [review]
Hey, I want only one entry by a contributor. If you want to edit your previous entry, you can do that. Otherwise, I'll close the PR.

**Comment by Akilan19** [comment]
ohkk :)

**Pull request closed without merging**
