### PR TITLE
Feat/logo added

### PR DESCRIPTION
**Pull request by Alekhya-Dharam**
This PR added the logo and made some font changes to the title.

**Fixes** #1 

**Screenshot**
**Before**:
before

**After**:
after

### CODE REVIEW

**Comment by Alekhya-Dharam** [comment]
Can u pls add the label **Hactoberfest** to this issue and pls merge it

**Review by aditeyaS — CHANGES_REQUESTED** [review]
Please remove the file - Untitled_logo_1_free-file.jpg as it is not being used.
And can you give a better name to img.jpg? logo.jpg or something

**Comment by Alekhya-Dharam** [comment]
> Please remove the file - Untitled_logo_1_free-file.jpg as it is not being used. And can you give a better name to img.jpg? logo.jpg or something

sure

**Review by Alekhya-Dharam — COMMENTED** [review]
Required changes made

**Pull request closed without merging**
