### PR TITLE
feat(choice): add AirOne01's choice

### PR DESCRIPTION
**Pull request by airone01**

### CODE REVIEW

**Comment by aditeyaS** [comment]
Can you please update contributors.md as well

**Review by aditeyaS — CHANGES_REQUESTED** [review]
Can you please update contributors.md as well

**Comment by aditeyaS** [comment]
Hey @AirOne01 shall I close the PR? Or you will be making the changes?

**Comment by airone01** [comment]
@aditeyaS Yeah sorry, had a lot of stuff to do. I made my changes to `contributors.md` and resolved conflicts.

**Review by aditeyaS — APPROVED** [review]

**Pull request merged**
